export const PORTRAIT_REGISTRY: {
  [key:string]: string;
} = {
  "no-portrait": "no-portrait.png",
  "dwarf-barbarian": "dwarf-barbarian.png",
  "dwarf-bard": "dwarf-bard.png",
  "dwarf-cleric": "dwarf-cleric.png",
  "dwarf-druid": "dwarf-druid.png",
  "dwarf-fighter": "dwarf-fighter.png",
  "dwarf-monk": "dwarf-monk.png",
  "dwarf-paladin": "dwarf-paladin.png",
  "dwarf-ranger": "dwarf-ranger.png",
  "dwarf-rogue": "dwarf-rogue.png",
  "dwarf-sorcerer": "dwarf-sorcerer.png",
  "dwarf-warlock": "dwarf-warlock.png",
  "dwarf-wizard": "dwarf-wizard.png",
  "elf-barbarian": "elf-barbarian.png",
  "elf-bard": "elf-bard.png",
  "elf-cleric": "elf-cleric.png",
  "elf-druid": "elf-druid.png",
  "elf-fighter": "elf-fighter.png",
  "elf-monk": "elf-monk.png",
  "elf-paladin": "elf-paladin.png",
  "elf-ranger": "elf-ranger.png",
  "elf-rogue": "elf-rogue.png",
  "elf-sorcerer": "elf-sorcerer.png",
  "elf-warlock": "elf-warlock.png",
  "elf-wizard": "elf-wizard.png",
  "halfling-barbarian": "halfling-barbarian.png",
  "halfling-bard": "halfling-bard.png",
  "halfling-cleric": "halfling-cleric.png",
  "halfling-druid": "halfling-druid.png",
  "halfling-fighter": "halfling-fighter.png",
  "halfling-monk": "halfling-monk.png",
  "halfling-paladin": "halfling-paladin.png",
  "halfling-ranger": "halfling-ranger.png",
}
